### ISSUE TITLE
Comments Toggle Not Functional on Newer Chrome

### ISSUE THREAD

**Issue by cyberrufus** [noplanman/Reddit-Plus#14]
![comment](https://cloud.githubusercontent.com/assets/4472374/10187081/bc06e00e-6723-11e5-8c32-f939f58d5e3c.png)

Comments toggle not functional in Chrome versions 47.0.2520.0 and higher.

**Comment by noplanman** [comment]
Thanks for letting me know. Could you please also tell me what operating system you are on?
For Windows and Mac the latest version of Chrome is 45.0.2454.101.
Do you have a pre-release version?

**Comment by cyberrufus** [comment]
Windows 10 x64. Issue existed in Canary build for a while and just bled over to the Developmental build last night with an update. Issue not present in Beta and Stable builds.

**Comment by noplanman** [comment]
I have only been testing with Stable builds, but keeping an eye on the dev build sure seems like a good idea! :+1: 

Are you using Tampermonkey?

**Comment by cyberrufus** [comment]
Yes, Tampermonkey stable. May well be a bug in Chrome that they'll iron out by the time it hits Stable but just wanted you to be aware of it.

**Comment by cyberrufus** [comment]
Issue has bled into the stable build just released this afternoon (47.0.2526.73 (64-bit)).

**Comment by noplanman** [comment]
@cyberrufus You're right that the issue bled over to stable, but updating Tampermonkey resolves that issue now.
If you agree with me, I'll close this issue as it's not a userscript problem.

**Comment by cyberrufus** [comment]
Script is now functioning in all builds of Chrome from Canary on down. Feel free to close it and thanks for your assistance.

**Comment by noplanman** [comment]
Great, thanks a lot for reporting!
Aaaaand, closed..
